greeting:
  message: "hello"
quarkus:
  log:
    file:
      enable: false
  kubernetes:
    ingress:
      tls:
        wildcard.com:
          enabled: true
      expose: true
    image-pull-secrets: "read-container-registry"
  datasource:
    db-kind: "postgresql"
  hibernate-orm:
    database:
      generation: "update"
  flyway:
    migrate-at-start: true
    baseline-description: "${quarkus.application.name}"
    baseline-version: 1.0
    connect-retries: 10
    baseline-on-migrate: true
    table: "flyway_quarkus_history"